{
    "name": "Aerotec - Aprobación de Compras",
    "version": "18.0.1.0.1",
    "category": "Accounting/Accounting",
    "summary": "Autorización por monto en facturas de proveedor y pagos, y gestión de productos por proveedor",
    "author": "Sebastian Rios / Aerotec Argentina SA",
    "license": "LGPL-3",
    "depends": ["account", "mail"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/aerotec_approval_rule_views.xml",
        "views/aerotec_supplier_product_views.xml",
        "views/account_move_views_inherit.xml",
        "views/account_payment_views_inherit.xml",
        "views/res_partner_views_inherit.xml",
        "views/menus.xml",
    ],
    "installable": True,
    "auto_install": False,
}
